# permissions for end users to edit ddbctldpjobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ddbctldpjob-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: dynamoctl-dp-operator
    app.kubernetes.io/part-of: dynamoctl-dp-operator
    app.kubernetes.io/managed-by: kustomize
  name: ddbctldpjob-editor-role
rules:
- apiGroups:
  - dynamoctl.dp.operators.sanjivmadhavan.io
  resources:
  - ddbctldpjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamoctl.dp.operators.sanjivmadhavan.io
  resources:
  - ddbctldpjobs/status
  verbs:
  - get
