---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - dynamoctl.dp.operators.sanjivmadhavan.io
  resources:
  - ddbctldpjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dynamoctl.dp.operators.sanjivmadhavan.io
  resources:
  - ddbctldpjobs/finalizers
  verbs:
  - update
- apiGroups:
  - dynamoctl.dp.operators.sanjivmadhavan.io
  resources:
  - ddbctldpjobs/status
  verbs:
  - get
  - patch
  - update
