apiVersion: dynamoctl.dp.operators.sanjivmadhavan.io/v1alpha1
kind: DdbctlDpJob
metadata:
  labels:
    app.kubernetes.io/name: dynamoctl-dp-operator
    app.kubernetes.io/managed-by: kustomize
  name: ddbctldpjob-sample
spec:
  # TODO(user): Add fields here
